### ISSUE TITLE
Only set the cookie based on specific sources

### ISSUE THREAD

**Issue by Zuluru** [tboronczyk/localization-middleware#13]
I really like the idea of this implementation, but I'm struggling a bit with incorporating it into my system. What I'd like to be able to do with it is:
- Set the locale very early in the middleware queue based on cookie or header
- Override that locale selection using a per-user setting, but this must be done later in the queue after authentication has been done
- Set the cookie only in the case of a per-user setting, not when the locale is chosen based on the header
- Unset the cookie as the queue unwinds, if the user logged out

As far as I can tell, this can only be accomplished with a combination of:
- two separately-configured copies of the middleware inserted at different places in the queue
- changing the logic to allow for a default not to be set (can be done now in the locale callback)
- allowing for the locale callback to return an indication that the cookie should not be set (I guess I could do this by throwing an exception in my callback, and wrapping the call to the middleware in a function that catches and ignores this exception, but that just really feels kludgy)

So, my question is, is there a clean way to do what I'm thinking of already and I'm just missing it? If not, does some of this sound generally useful if I were to do a PR?

**Comment by Zuluru** [comment]
Any thoughts on this, anyone?

**Comment by tboronczyk** [comment]
Apologies for the delay.

Perhaps we could capture the return of the localeCallback in `__invoke()`? That would afford us an injectable way to modify the locale before it is set to the cookie.

    public function __invoke(Request $req, Response $resp, callable $next)
    {
        $locale = $this->getLocale($req);
        $locale = $this->localeCallback->__invoke($locale);
        $req = $req->withAttribute($this->reqAttrName, $locale);
    ...

I would certainly welcome a PR even if only to more clearly see your proposal.

**Comment by Zuluru** [comment]
I'll aim to put something together in the next couple of days.

**Comment by tboronczyk** [comment]
closed due to lack of activity.
